name: CI
on: pull_request
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: Brightspace/third-party-actions@actions/checkout
      - name: Setup Node
        uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version-file: .nvmrc
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run test:lint
      - name: Unit Tests
        run: npx web-test-runner --config web-test-runner.config.js --group default --playwright --browsers chromium firefox webkit
